version: "2"
services:

  #  MongoDb for development purposes
  mongo-db:
    image: 'bitnami/mongodb:4.0-ol-7'
    mem_limit: 256m
    ports:
      - "27017:27017"
    volumes:
      - ./databases/mongodb:/data/db


  #  Rabbitmq for development purposes
  rabbitmq-management:
    image: rabbitmq:3-management
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672


      # MySql db
  mySql-db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_DATABASE: 'symfony_fd_core_booking'
      MYSQL_ROOT_PASSWORD: 'asdasd'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - /.docker/volumes/db/mysql/data
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4',
              '--collation-server=utf8mb4_unicode_ci']

      # Postgres db with postgis
  postgres-postgis-db-11:
    container_name: postgres-postgis-11
    image: kartoza/postgis:11.0-2.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root-p
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,unaccent
    ports:
      - 5432:5432
    volumes:
      - /.docker/volumes/db/potgres/data
